package com.example.navigation_drawer

const val NAME="Name"
const val EMAIL="EMAIL_ADDRESS"
const val BITMAPIMAGE="Bitmapimage"
const val IMAGEFROMGALLERY="Cameraimage"
const val PASSWORD="Password"
const val TOKEN="Token"
const val GALLERY="Gallery"
const val CAMERA="Camera"
const val IMAGE_TYPE="image/*"
const val ERROR="Error! Empty String"
const val CHECK="Check"
const val TAG="MyCustomFragment"
const val PAGENOTFOUND="Page Is Not Avaliable"
const val SUCCESSFUL="Successful "
const val FAIL="Failed "
const val MY_PREFERENCE="My Preferences"
const val NOT_LOGIN="Error! Incorrect Email Or Password"
const val CHECKFORBITMAP="CheckForBitMap"
const val LOGOUT="Log_out"
const val CHECKFORREGISTER="Check_For_Register"
const val POSITION="Position"
const val LOCATION="Location"
const val DATE="Date"
const val PICTURE="Picture"
const val ID="Id"